# Generated by Django 5.1 on 2024-08-29 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0002_contact_phone_contact_subject'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'verbose_name': 'contact', 'verbose_name_plural': 'contact_us'},
        ),
        migrations.AlterField(
            model_name='contact',
            name='phone',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
