# Generated by Django 5.1 on 2024-08-30 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0003_alter_contact_options_alter_contact_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='google',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
